const { expect } = require("chai");
const { ethers } = require("hardhat");
const { time } = require("@nomicfoundation/hardhat-network-helpers");

describe("GoldenHour contracts", function () {
  async function deploy() {
    const [owner, patient, doctor, stranger] = await ethers.getSigners();
    const Registry=await ethers.getContractFactory("PatientRegistry");const registry=await Registry.deploy(owner.address);
    const Access=await ethers.getContractFactory("contracts/AccessControl.sol:AccessControl");const access=await Access.deploy(owner.address,await registry.getAddress());
    const Records=await ethers.getContractFactory("MedicalRecord");const records=await Records.deploy(await access.getAddress(),owner.address);
    const Audit=await ethers.getContractFactory("AuditLog");const audit=await Audit.deploy(owner.address);
    const Emergency=await ethers.getContractFactory("EmergencyAccess");const emergency=await Emergency.deploy(await registry.getAddress(),await access.getAddress(),await audit.getAddress(),owner.address);
    await audit.transferOwnership(await emergency.getAddress());await access.grantRole(await access.VERIFIER_ROLE(),owner.address);await access.grantRole(await access.VERIFIER_ROLE(),doctor.address);await access.connect(doctor).setProviderVerified(doctor.address,true);
    return{owner,patient,doctor,stranger,registry,access,records,audit,emergency};
  }
  it("registers unique patients and stores only hashes",async function(){const{registry,patient}=await deploy();await expect(registry.connect(patient).registerPatient(ethers.id("profile"),ethers.id("critical"))).to.emit(registry,"PatientRegistered");expect(await registry.getPatientId(patient.address)).to.equal(1);await expect(registry.connect(patient).registerPatient(ethers.id("x"),ethers.id("y"))).to.be.revertedWith("Already registered")});
  it("supports verified, time-bound access and append-only records",async function(){const{registry,access,records,patient,doctor}=await deploy();await registry.connect(patient).registerPatient(ethers.id("profile"),ethers.id("critical"));await expect(records.connect(doctor).addRecord(1,"allergy","ipfs://demo",ethers.id("encrypted"))).to.be.revertedWith("No patient access");await access.connect(patient).grantAccess(1,doctor.address,0);await records.connect(doctor).addRecord(1,"allergy","ipfs://demo",ethers.id("encrypted"));expect(await records.recordCount(1)).to.equal(1)});
  it("supports trusted relay operations without changing wallet ownership semantics",async function(){const{registry,access,records,emergency,owner,patient,doctor}=await deploy();await registry.connect(owner).registerPatientFor(patient.address,ethers.id("profile"),ethers.id("critical"));expect(await registry.getPatientId(patient.address)).to.equal(1);await access.connect(owner).grantAccessFor(patient.address,1,doctor.address,0);await records.connect(owner).addRecordFor(1,doctor.address,"lab","ipfs://demo",ethers.id("encrypted"));expect(await records.recordCount(1)).to.equal(1);await emergency.connect(owner).triggerEmergencyAccessFor(1,doctor.address,"Relay emergency access justification");});
  it("rejects unverified providers and enforces patient ownership",async function(){const{registry,access,patient,doctor,stranger}=await deploy();await registry.connect(patient).registerPatient(ethers.id("profile"),ethers.id("critical"));await expect(access.connect(stranger).grantAccess(1,doctor.address,0)).to.be.revertedWith("Not patient owner");await expect(access.connect(patient).grantAccess(1,stranger.address,0)).to.be.revertedWith("Provider not verified");await expect(access.connect(patient).grantAccess(1,doctor.address,1)).to.be.revertedWith("Invalid expiry")});
  it("supports expiry and revocation",async function(){const{registry,access,patient,doctor}=await deploy();await registry.connect(patient).registerPatient(ethers.id("profile"),ethers.id("critical"));const expiry=(await time.latest())+60;await access.connect(patient).grantAccess(1,doctor.address,expiry);expect(await access.checkAccess(1,doctor.address)).to.equal(true);await time.increaseTo(expiry+1);expect(await access.checkAccess(1,doctor.address)).to.equal(false);await access.connect(patient).grantAccess(1,doctor.address,0);await access.connect(patient).revokeAccess(1,doctor.address);expect(await access.checkAccess(1,doctor.address)).to.equal(false)});
  it("logs justified emergency access",async function(){const{registry,access,audit,emergency,patient,doctor}=await deploy();await registry.connect(patient).registerPatient(ethers.id("profile"),ethers.id("critical"));await expect(emergency.connect(doctor).triggerEmergencyAccess(1,"Unconscious trauma patient")).to.emit(emergency,"EmergencyTriggered");expect(await audit.entryCount(1)).to.equal(1)});
});
