import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { QRCodeSVG } from "qrcode.react";
import "./styles.css";

const demoPatient = { id: "GH-001", name: "Demo Patient", bloodGroup: "O+", allergies: ["Penicillin"], conditions: ["Asthma"], medications: ["Salbutamol inhaler"] };
function App() {
  const [mode, setMode] = useState("patient"); const [notice, setNotice] = useState("");
  const handleEmergency = () => { setNotice("Emergency access request recorded. Critical fields are shown below for this demo."); setMode("emergency"); };
  return <div className="app"><header><div className="brand"><span className="mark">GH</span><div><strong>GoldenHour</strong><small>Trusted emergency history</small></div></div><nav>{["patient", "doctor", "emergency"].map((item) => <button className={mode === item ? "active" : ""} onClick={() => setMode(item)} key={item}>{item === "emergency" ? "Emergency access" : `${item[0].toUpperCase()}${item.slice(1)} portal`}</button>)}</nav><button className="wallet" onClick={() => setNotice("Wallet connection is ready for MetaMask integration.")}>Connect wallet</button></header><main><section className="hero"><div><p className="eyebrow">Every second matters</p><h1>Medical context when <em>minutes matter.</em></h1><p className="lead">A privacy-first emergency record system. Encrypted records stay off-chain while verifiable hashes and every access event remain auditable.</p><div className="hero-actions"><button className="primary" onClick={() => setMode("patient")}>Open patient dashboard</button><button className="secondary" onClick={handleEmergency}>Enter emergency flow</button></div></div><div className="hero-card"><div className="pulse">● Live demo network</div><h3>Emergency lookup</h3><div className="lookup"><span>Scan patient QR</span><button onClick={handleEmergency}>→</button></div><div className="stats"><div><b>04.8s</b><span>target lookup</span></div><div><b>256-bit</b><span>encrypted files</span></div></div></div></section>{notice && <div className="notice">{notice}</div>}{mode === "patient" && <PatientDashboard />}{mode === "doctor" && <DoctorDashboard onEmergency={handleEmergency} />}{mode === "emergency" && <EmergencyView />}</main><footer><span>GoldenHour</span><span>On-chain audit • Off-chain encryption • Consent by design</span></footer></div>;
}
function PatientDashboard() { return <section className="dashboard"><div className="section-heading"><div><p className="eyebrow">Patient dashboard</p><h2>Your emergency profile</h2></div><span className="verified">● Verified identity</span></div><div className="grid"><article className="panel profile"><div className="avatar">DP</div><h3>{demoPatient.name}</h3><p className="muted">Patient ID {demoPatient.id}</p><div className="critical"><span>Blood group</span><strong>{demoPatient.bloodGroup}</strong></div><div className="qr"><QRCodeSVG value={`goldenhour://patient/${demoPatient.id}`} size={112}/><div><b>Emergency QR card</b><p>Share only with verified clinicians. This QR reveals critical fields through a logged break-glass flow.</p><button className="text-button">Download card →</button></div></div></article><article className="panel"><h3>Critical medical context</h3><DataRow title="Allergies" values={demoPatient.allergies} danger/><DataRow title="Chronic conditions" values={demoPatient.conditions}/><DataRow title="Current medications" values={demoPatient.medications}/><div className="privacy-note">Your clinical files are encrypted before off-chain storage. The blockchain stores only integrity hashes and access events.</div></article><article className="panel wide"><div className="panel-head"><h3>Record timeline</h3><button className="secondary small">+ Add record</button></div><div className="timeline"><div><span>12 Jun 2026</span><b>Annual respiratory review</b><small>City General Hospital • Dr. A. Kumar</small></div><div><span>04 Feb 2026</span><b>Medication prescription</b><small>Northside Clinic • Dr. M. Rao</small></div></div></article></div></section> }
function DataRow({title, values, danger}) { return <div className="data-row"><span>{title}</span><div>{values.map(v => <b className={danger ? "tag danger" : "tag"} key={v}>{v}</b>)}</div></div> }
function DoctorDashboard({onEmergency}) { return <section className="dashboard"><div className="section-heading"><div><p className="eyebrow">Verified clinician portal</p><h2>Care team workspace</h2></div><span className="verified">● Provider verified</span></div><div className="doctor-grid"><div className="panel search-panel"><h3>Find a patient</h3><p className="muted">Search by GoldenHour ID or scan a patient QR.</p><input placeholder="GH-001"/><button className="primary full">Request consented access</button><button className="secondary full" onClick={onEmergency}>Use emergency access</button></div><div className="panel"><h3>Access activity</h3><div className="activity"><span className="activity-dot"></span><div><b>Record viewed</b><p>Patient GH-001 • 2 minutes ago</p></div><code>CONSENTED</code></div><div className="activity"><span className="activity-dot amber"></span><div><b>Emergency access</b><p>Patient GH-009 • Yesterday</p></div><code>BREAK-GLASS</code></div><div className="privacy-note">Every read is timestamped, scoped, and visible in the patient's audit trail.</div></div></div></section> }
function EmergencyView() { return <section className="dashboard"><div className="emergency-banner"><span className="warning">!</span><div><b>Break-glass access active</b><p>Critical-only fields are available. This event is being written to the immutable audit trail.</p></div></div><div className="section-heading"><div><p className="eyebrow">Emergency scan result</p><h2>Patient {demoPatient.id}</h2></div><span className="verified">Access logged now</span></div><div className="critical-grid"><div><span>Blood group</span><strong>{demoPatient.bloodGroup}</strong></div><div><span>Allergies</span><strong>{demoPatient.allergies.join(", ")}</strong></div><div><span>Conditions</span><strong>{demoPatient.conditions.join(", ")}</strong></div><div><span>Medications</span><strong>{demoPatient.medications.join(", ")}</strong></div></div><div className="panel audit-panel"><h3>Access justification</h3><p className="muted">Unconscious trauma patient — critical history required for immediate treatment.</p><div className="audit-row"><span>Scope</span><b>EMERGENCY_CRITICAL_ONLY</b></div><div className="audit-row"><span>Timestamp</span><b>{new Date().toLocaleString()}</b></div></div></section> }
createRoot(document.getElementById("root")).render(<App />);
